DROP TABLE IF EXISTS users;
CREATE TABLE users
(
  id         INT(11) NOT NULL AUTO_INCREMENT,
  first_name VARCHAR(250),
  last_name  VARCHAR(250),
  email      VARCHAR(250),
  password   VARCHAR(250),
  created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (id)
) ENGINE = InnoDB
 DEFAULT CHARSET = utf8;